name: "Bump AWS docs submodules"
on:
  schedule:
    - cron: "0 4 * * *"      # every day at 04:00 UTC
  workflow_dispatch:
permissions:
  contents: write
  packages: write
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: |
          git submodule update --remote --merge
          if ! git diff --quiet; then
            git config user.name  "aws-docs-bot"
            git config user.email "aws-docs-bot@users.noreply.github.com"
            git commit -am "chore: daily AWS docs refresh"
            git push
          fi
